[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "Emi694pE9oyAt2iWchPW7ZjTcbpm22bSqNGF6dQ39WUg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/truongnguyen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
